### PR TITLE
Introduce GDB::Git::Wrapper

### PR DESCRIPTION
**Pull request by sergeyromanov**
I've just mimicked `Git::Repository` backend. The `ObjectReader`'s methods are not there yet, but this should be a start.

### CODE REVIEW

**Comment by sergeyromanov** [comment]
777cfe6 is really just a little discrepancy fix, I can re-apply in a different branch if you'd like so :)

**Comment by book** [comment]
I actually had a `git-wrapper` branch already with the `ObjectReader` role, but hadn't pushed it yet. I've pushed it now, and I'll integrate your additions soon. They seem to complement nicely.

**Comment by book** [comment]
I've applied 777cfe69175ce6bd30f7b7e61ba4e4a23f6058e8 independently as 8f27d2102edcc8f5727de39df1704a627eaff9e9. Thanks!

**Comment by book** [comment]
I've applied 397aff46fb9d357c6bce441f28a16b25a0647192 as 78ab99afb826aa03da8604acb0f9db534309fd75.

**Comment by book** [comment]
With both those commits applied to the main repository, I'm now closing this PR. Thanks to your patches, Git::Database::Backend::Git::Wrapper will be part of the next release.

**Pull request closed without merging**
